# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: mdp-pool1
  demands:
  - ImageOverride -equals ubuntu-24.04

strategy:
  matrix:
    Python310:
      python.version: '3.10'
    Python311:
      python.version: '3.11'
    Python312:
      python.version: '3.12'

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.x'

- script: |
    pip install build
    pip install twine
  displayName: 'Install build and twine'

- script: |
    python -m build -w
  displayName: 'Python build'

- task: TwineAuthenticate@1
  inputs:
    artifactFeed: test-mdp/sr-mdp-demo               ## For an organization-scoped feed, use: artifactFeed: <FEED_NAME>
  displayName: 'Twine Authenticate'

- script: |
    python -m twine upload -r sr-mdp-demo --config-file $(PYPIRC_PATH) dist/*.whl
  displayName: 'Upload to feed'
