# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: mdp-pool1
  demands:
  - ImageOverride -equals ubuntu-24.04

variables:
  pythonVersion: "3.11"

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: $(pythonVersion)
  displayName: 'Use Python $(pythonVersion)'

- script: |
    pip install build
    pip install twine
  displayName: 'Install build and twine'

- script: |
    python -m build -w
  displayName: 'Python build'

- task: TwineAuthenticate@1
  inputs:
    artifactFeed: test-mdp/pipit-feed               ## For an organization-scoped feed, use: artifactFeed: <FEED_NAME>
  displayName: 'Twine Authenticate'

# - script: |
#     python -m twine upload -r pipit-feed --config-file $(PYPIRC_PATH) dist/*.whl
#   displayName: 'Upload to feed'

# Docker v2
# Build or push Docker images, login or logout, start or stop containers, or run a Docker command.
- task: Docker@2
  inputs:
  # Container Repository
    #containerRegistry: # string. Container registry. 
    #repository: # string. Optional. Use when command != login && command != logout && command != start && command != stop. Container repository. 
  # Commands
    command: 'build' # 'buildAndPush' | 'build' | 'push' | 'login' | 'logout' | 'start' | 'stop'. Required. Command. Default: buildAndPush.
    Dockerfile: '**/Dockerfile' # string. Required when command = build || command = buildAndPush. Dockerfile. Default: **/Dockerfile.
    #buildContext: '**' # string. Optional. Use when command = build || command = buildAndPush. Build context. Default: **.
    tags: '$(Build.BuildId)' # string. Optional. Use when command = build || command = push || command = buildAndPush. Tags. Default: $(Build.BuildId).
    #arguments: # string. Optional. Use when command != login && command != logout && command != buildAndPush. Arguments. 
    addPipelineData: true # boolean. Add Pipeline metadata to image(s). Default: true.
    addBaseImageData: true # boolean. Add base image metadata to image(s). Default: true.
    container: mdp-demo # string. Optional. Use when command = start || command = stop.
