# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  name: mdp-pool1
  demands:
  - ImageOverride -equals ubuntu-24.04

variables:
  pythonVersion: "3.11"

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: $(pythonVersion)
  displayName: 'Use Python $(pythonVersion)'

- script: |
    pip install build
    pip install twine
    pip install setuptools
  displayName: 'Install build, setuptools and twine'

- script: |
    python setup.py --version
    echo $(python setup.py --version).$(Build.BuildId)
    echo "##vso[task.setvariable variable=APP_VERSION]$(python setup.py --version).$(Build.BuildId)"
  displayName: 'create app version'

- script: |
    echo "APP_VERSION=$(APP_VERSION)"
    echo "__version__='$(APP_VERSION)'" > version.py
    python setup.py --version
  displayName: 'Setup distribution version'
  

- script: |
    python -m build -w
  displayName: 'Python build'

- task: TwineAuthenticate@1
  inputs:
    artifactFeed: {your artifact feed name}              ## For an organization-scoped feed, use: artifactFeed: <FEED_NAME>
  displayName: 'Twine Authenticate'

- script: |
    python -m twine upload -r {your artifact feed name} --config-file $(PYPIRC_PATH) dist/*.whl
  displayName: 'Upload to feed'


